### ISSUE TITLE
请问手机端要怎么设置小爱和blinker，我的会报参数错误

### ISSUE THREAD

**Issue by myhalo** [xinruoyusixian/Blinker-for-xiaoai#1]
Mqtt发送>>>> {"deviceType": "OwnApp", "data": "{\"state\":\"connected\"}", "toDevice": "3f702f82aff5a647faa1660b317fb3eb", "fromDevice": "D7EDB3FEC7AQAVA4ULENA25W"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 195, in <module>
  File "/lib/robust2.py", line 273, in check_msg
  File "/lib/simple2.py", line 478, in check_msg
  File "/lib/robust2.py", line 262, in wait_msg
  File "/lib/simple2.py", line 459, in wait_msg
TypeError: function takes 2 positional arguments but 4 were given

**Comment by xinruoyusixian** [comment]
发送的数据有问题吧  看到报错信息是函数需要2个参数您给了4个

**Comment by myhalo** [comment]
> 发送的数据有问题吧 看到报错信息是函数需要2个参数您给了4个

嗯，找到问题了，是我用的mqtt库有问题，已解决
